const $=(s,e=document)=>e.querySelector(s), $$=(s,e=document)=>[...e.querySelectorAll(s)];
const STORAGE='hmHybridPilot_v1'; let DATA=null; let state=load(); let currentRoute='home'; let timerId=null;
function defaultState(){return {athlete:'Pilot Athlete',week:1,logs:{},feedback:{},settings:{units:'lb'}}}
function load(){try{return {...defaultState(),...JSON.parse(localStorage.getItem(STORAGE)||'{}')}}catch{return defaultState()}}
function save(){localStorage.setItem(STORAGE,JSON.stringify(state))}
function key(week,day,exercise){return `${week}|${day}|${exercise}`}
function logFor(w,d,e){return state.logs[key(w,d,e)]||{}}
function phaseFor(w){return DATA.progression.phases.find(p=>p.weeks.includes(+w))||DATA.progression.phases[0]}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(t._x);t._x=setTimeout(()=>t.classList.remove('show'),1800)}
function setRoute(route){currentRoute=route; $$('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.route===route)); if(route==='home') renderHome(); if(route==='progress') renderProgress(); if(route==='feedback') renderFeedback(); if(route==='guide') renderGuide(); window.scrollTo({top:0,behavior:'smooth'})}
function escapeHtml(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function pctDay(w,day){const ex=day.weeks[String(w)]||[]; if(!ex.length)return 0; const done=ex.filter(x=>logFor(w,day.id,x.exercise).complete).length; return Math.round(done/ex.length*100)}
function weekDone(w){return DATA.days.filter(d=>pctDay(w,d)===100).length}
function renderHome(){const p=phaseFor(state.week); $('#view').innerHTML=`
  <section class="hero"><div class="eyebrow">High Mileage Hybrid 1.1</div><h1>TRAIN FOR<br>THE MILES AHEAD.</h1><p>Strength. Power. Athleticism. Conditioning. Recovery. Log the work, earn the progression, and stay capable.</p></section>
  <div class="week-row">${[1,2,3,4,5,6,7,8].map(w=>`<button class="week-chip ${w===+state.week?'active':''}" data-week="${w}">W${w}</button>`).join('')}</div>
  <div class="phase-card"><b>${p.name} PHASE · WEEKS ${p.weeks.join('–')}</b><span>${p.emphasis}</span></div>
  <div class="section-title"><h2>Week ${state.week}</h2><small>${weekDone(state.week)}/5 sessions complete</small></div>
  <div class="day-grid">${DATA.days.map((d,i)=>{let pc=pctDay(state.week,d); return `<article class="day-card ${pc===100?'done':''}" data-day="${d.id}"><div><div class="eyebrow">DAY ${i+1}</div><h3>${escapeHtml(d.title)}</h3><p>${d.weeks[String(state.week)].length} movements · ${pc}% logged</p></div><span class="tag">${pc===100?'COMPLETE':'OPEN'}</span><div class="meter"><i style="width:${pc}%"></i></div></article>`}).join('')}</div>`;
  $$('.week-chip').forEach(b=>b.onclick=()=>{state.week=+b.dataset.week;save();renderHome()});
  $$('.day-card').forEach(c=>c.onclick=()=>renderWorkout(c.dataset.day));
}
function parseRange(target){const m=String(target||'').match(/(\d+)\s*[–-]\s*(\d+)(?!.*\d)/); if(m)return {min:+m[1],max:+m[2]}; const nums=String(target||'').match(/\d+/g); return nums?.length?{min:+nums.at(-1),max:+nums.at(-1)}:null}
function roundTo(x,inc){return Math.round(x/inc)*inc}
function suggestion(w,day,ex){if(w<=1)return null; if(!['STRENGTH','BUILD'].includes(ex.block))return null; const prev=logFor(w-1,day.id,ex.exercise); const wt=parseFloat(prev.weight), reps=parseFloat(prev.reps), rir=parseFloat(prev.rir); if(!Number.isFinite(wt)||!Number.isFinite(reps)||!Number.isFinite(rir))return {text:'Log prior week to unlock load suggestion'}; const rr=parseRange(ex.target); if(!rr)return null; const s=DATA.progression.settings; let mult=1,reason='Hold load and beat reps';
  if(ex.block==='STRENGTH'){if(reps>=rr.max&&rir>=s.strengthRirMin&&rir<=s.strengthRirMax){mult=1+s.strengthIncrease;reason='Top target at 1–2 RIR'} else if(reps>=rr.max&&rir>s.strengthRirMax){mult=1+s.highRirIncrease;reason='Top target with extra RIR'} else if(reps<rr.min&&rir===0){mult=1-s.missFloorReduction;reason='Rep floor missed at 0 RIR'}}
  if(ex.block==='BUILD'){if(reps>=rr.max&&rir<=s.buildRirMax){mult=1+s.buildIncrease;reason='Top target at 0–1 RIR'} else if(reps>=rr.max&&rir>s.buildRirMax){mult=1+s.highRirIncrease;reason='Top target with extra RIR'} else if(reps<rr.min&&rir===0){mult=1-s.missFloorReduction;reason='Rep floor missed at 0 RIR'}}
  const val=roundTo(wt*mult,s.rounding); return {value:val,text:`Suggested ${val} ${state.settings.units} · ${reason}`};
}
function renderWorkout(dayId){const day=DATA.days.find(d=>d.id===dayId), exs=day.weeks[String(state.week)]||[]; currentRoute='workout'; $$('.nav-btn').forEach(b=>b.classList.remove('active')); let lastBlock='';
  $('#view').innerHTML=`<div class="workout-head"><button class="back-btn" id="backHome">←</button><div><h1>${escapeHtml(day.title)}</h1><p>WEEK ${state.week} · ${phaseFor(state.week).name}</p></div></div><div id="exerciseList">${exs.map((ex,idx)=>{const log=logFor(state.week,day.id,ex.exercise), sug=suggestion(state.week,day,ex); let block=''; if(ex.block!==lastBlock){lastBlock=ex.block;block=`<div class="block-title">${escapeHtml(ex.block)}</div>`} return block+exerciseCard(day,ex,idx,log,sug)}).join('')}</div><button class="complete-workout" id="finishWorkout">MARK SESSION COMPLETE</button>`;
  $('#backHome').onclick=()=>setRoute('home');
  $$('.exercise-card').forEach(card=>wireExerciseCard(card,day));
  $('#finishWorkout').onclick=()=>{exs.forEach(ex=>{const k=key(state.week,day.id,ex.exercise);state.logs[k]={...state.logs[k],complete:true,date:state.logs[k]?.date||new Date().toISOString().slice(0,10)}});save();toast('Session marked complete');renderWorkout(day.id)}
}
function exerciseCard(day,ex,idx,log,sug){return `<article class="exercise-card ${log.complete?'complete':''}" data-ex="${escapeHtml(ex.exercise)}"><div class="exercise-top"><button class="check" title="Mark complete">${log.complete?'✓':''}</button><div class="exercise-name"><button class="exercise-info">${escapeHtml(ex.exercise)}</button><small>${escapeHtml(ex.block)}</small></div></div><div class="specs"><div class="spec"><b>TARGET</b><span>${escapeHtml(ex.target)}</span></div><div class="spec"><b>TEMPO</b><span>${escapeHtml(ex.tempo)}</span></div><div class="spec"><b>REST</b><span>${escapeHtml(ex.rest)}</span></div></div><div class="cue">${escapeHtml(ex.cue||'')}</div><div class="log-grid"><div class="field"><label>Weight / Load</label><input inputmode="decimal" class="weight" value="${escapeHtml(log.weight||'')}" placeholder="—"></div><div class="field"><label>Actual Reps / Time</label><input inputmode="decimal" class="reps" value="${escapeHtml(log.reps||'')}" placeholder="—"></div><div class="field"><label>Actual RIR</label><input inputmode="decimal" class="rir" value="${escapeHtml(log.rir||'')}" placeholder="—"></div><div class="field notes-field"><label>Notes / Next Target</label><textarea class="notes" placeholder="How did it feel?">${escapeHtml(log.notes||'')}</textarea></div></div>${sug?`<div class="suggestion"><span>${escapeHtml(sug.text)}</span>${sug.value?`<button class="use-suggestion" data-value="${sug.value}">USE</button>`:''}</div>`:''}${parseRestSeconds(ex.rest)?`<button class="rest-btn" data-seconds="${parseRestSeconds(ex.rest)}">REST TIMER · ${formatTime(parseRestSeconds(ex.rest))}</button>`:''}</article>`}
function wireExerciseCard(card,day){const exName=card.dataset.ex, k=key(state.week,day.id,exName); const persist=()=>{const old=state.logs[k]||{}; state.logs[k]={...old,weight:$('.weight',card).value,reps:$('.reps',card).value,rir:$('.rir',card).value,notes:$('.notes',card).value,date:old.date||new Date().toISOString().slice(0,10)};save()}; ['input','change'].forEach(evt=>$$('input,textarea',card).forEach(el=>el.addEventListener(evt,persist))); $('.check',card).onclick=()=>{persist();state.logs[k].complete=!state.logs[k].complete;save();card.classList.toggle('complete',state.logs[k].complete);$('.check',card).textContent=state.logs[k].complete?'✓':''}; $('.exercise-info',card).onclick=()=>showExercise(exName); $('.use-suggestion',card)?.addEventListener('click',e=>{$('.weight',card).value=e.currentTarget.dataset.value;persist();toast('Suggested load applied')}); $('.rest-btn',card)?.addEventListener('click',e=>startTimer(e.currentTarget,+e.currentTarget.dataset.seconds))}
function parseRestSeconds(v){v=String(v||'').toLowerCase(); if(v.includes('—')||v.includes('as prescribed'))return 0; let m=v.match(/(\d+)\s*[–-]\s*(\d+)\s*sec/); if(m)return +m[2]; m=v.match(/(\d+)\s*sec/); if(m)return +m[1]; m=v.match(/(\d+)\s*[–-]\s*(\d+)\s*min/); if(m)return +m[2]*60; m=v.match(/(\d+)\s*min/); if(m)return +m[1]*60; return 0}
function formatTime(s){return `${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`}
function startTimer(btn,seconds){clearInterval(timerId);let left=seconds;btn.textContent=`REST · ${formatTime(left)}`;timerId=setInterval(()=>{left--;btn.textContent=`REST · ${formatTime(Math.max(left,0))}`;if(left<=0){clearInterval(timerId);btn.textContent='REST COMPLETE ✓';navigator.vibrate?.([100,70,100]);toast('Rest complete')}} ,1000)}
function showExercise(name){const g=DATA.guide[name]||{}; const d=$('#exerciseModal');d.innerHTML=`<button class="modal-close">×</button><div class="modal-inner"><div class="quality">${escapeHtml(g.quality||'EXERCISE')}</div><h2>${escapeHtml(name)}</h2><p><strong>How to perform</strong><br>${escapeHtml(g.how||'Use the workout cue and maintain controlled, repeatable technique.')}</p><p><strong>Key cue</strong><br>${escapeHtml(g.cue||'')}</p><p><strong>Avoid</strong><br>${escapeHtml(g.avoid||'Technique breakdown or forced range.')}</p></div>`; $('.modal-close',d).onclick=()=>d.close();d.showModal()}
function renderProgress(){let total=0,done=0; DATA.days.forEach(d=>{for(let w=1;w<=8;w++){total++;if(pctDay(w,d)===100)done++}}); $('#view').innerHTML=`<div class="section-title"><h2>Pilot Progress</h2><small>${escapeHtml(state.athlete)}</small></div><div class="stat-grid"><div class="stat"><b>${done}</b><small>sessions complete</small></div><div class="stat"><b>${Math.round(done/total*100)}%</b><small>program complete</small></div><div class="stat"><b>W${state.week}</b><small>current week</small></div></div>${[1,2,3,4,5,6,7,8].map(w=>{let n=weekDone(w);return `<div class="week-progress"><div class="week-progress-head"><b>Week ${w} · ${phaseFor(w).name}</b><span>${n}/5</span></div><div class="bar"><i style="width:${n/5*100}%"></i></div></div>`}).join('')}<button class="full-btn" id="exportBtn">EXPORT PILOT DATA (.JSON)</button><button class="full-btn" id="exportCsv">EXPORT WORKOUT LOG (.CSV)</button>`; $('#exportBtn').onclick=exportJson;$('#exportCsv').onclick=exportCsv}
function renderFeedback(){const f=state.feedback[String(state.week)]||{}; const metric=(id,label)=>`<div class="feedback-card"><h3>${label}</h3><div class="rating-row" data-rating="${id}">${[1,2,3,4,5].map(n=>`<button class="${+f[id]===n?'selected':''}" data-value="${n}">${n}</button>`).join('')}</div></div>`; $('#view').innerHTML=`<div class="section-title"><h2>Week ${state.week} Pilot Feedback</h2><small>1 = low · 5 = high</small></div>${metric('intensity','Training intensity')}${metric('athletic','Athletic feel')}${metric('flow','Workout flow')}${metric('recovery','Recovery / readiness')}${metric('fulfillment','Enjoyment / fulfillment')}<div class="feedback-card"><h3>What worked? What needs changed?</h3><div class="field"><textarea id="feedbackNotes" style="min-height:130px" placeholder="Exercises, volume, intensity, soreness, time, substitutions...">${escapeHtml(f.notes||'')}</textarea></div><button class="full-btn" id="saveFeedback">SAVE WEEK ${state.week} FEEDBACK</button></div>`; $$('.rating-row button').forEach(b=>b.onclick=()=>{const row=b.parentElement;$$('button',row).forEach(x=>x.classList.remove('selected'));b.classList.add('selected');const ff=state.feedback[String(state.week)]||{};ff[row.dataset.rating]=+b.dataset.value;state.feedback[String(state.week)]=ff;save()});$('#saveFeedback').onclick=()=>{const ff=state.feedback[String(state.week)]||{};ff.notes=$('#feedbackNotes').value;ff.savedAt=new Date().toISOString();state.feedback[String(state.week)]=ff;save();toast('Feedback saved')}}
function renderGuide(){const entries=Object.entries(DATA.guide); $('#view').innerHTML=`<div class="section-title"><h2>Exercise Guide</h2><small>${entries.length} movements</small></div><input class="guide-search" id="guideSearch" placeholder="Search an exercise..."><div class="guide-list" id="guideList">${entries.map(([n,g])=>`<div class="guide-item" data-name="${escapeHtml(n)}"><b>${escapeHtml(n)}</b><small>${escapeHtml(g.quality||'')}</small></div>`).join('')}</div>`; const wire=()=>$$('.guide-item').forEach(x=>x.onclick=()=>showExercise(x.dataset.name));wire();$('#guideSearch').oninput=e=>{const q=e.target.value.toLowerCase();$$('.guide-item').forEach(x=>x.style.display=x.dataset.name.toLowerCase().includes(q)?'block':'none')}}
function exportJson(){download(`high-mileage-pilot-${slug(state.athlete)}.json`,JSON.stringify({program:DATA.program,athlete:state.athlete,exportedAt:new Date().toISOString(),logs:state.logs,feedback:state.feedback},null,2),'application/json')}
function exportCsv(){let rows=[['Week','Day','Exercise','Block','Weight','Actual Reps/Time','RIR','Complete','Date','Notes']];for(let w=1;w<=8;w++)DATA.days.forEach(d=>d.weeks[String(w)].forEach(ex=>{const l=logFor(w,d.id,ex.exercise);rows.push([w,d.title,ex.exercise,ex.block,l.weight||'',l.reps||'',l.rir||'',l.complete?'Yes':'No',l.date||'',l.notes||''])}));download(`high-mileage-workout-log-${slug(state.athlete)}.csv`,rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n'),'text/csv')}
function slug(s){return String(s||'pilot').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}
function download(name,content,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function showSettings(){const d=$('#settingsModal');d.innerHTML=`<button class="modal-close">×</button><div class="modal-inner"><h2>Pilot Settings</h2><div class="settings-card"><div class="field"><label>Athlete name</label><input id="athleteName" value="${escapeHtml(state.athlete)}"></div><div class="field" style="margin-top:12px"><label>Load units</label><select id="units"><option value="lb" ${state.settings.units==='lb'?'selected':''}>lb</option><option value="kg" ${state.settings.units==='kg'?'selected':''}>kg</option></select></div><button class="full-btn" id="saveSettings">SAVE SETTINGS</button></div><div class="settings-card"><p style="color:var(--muted);margin-top:0">All workout data is stored on this device. Export it from Progress before clearing browser data.</p><button class="full-btn danger-btn" id="resetData">RESET ALL PILOT DATA</button></div></div>`;$('.modal-close',d).onclick=()=>d.close();$('#saveSettings',d).onclick=()=>{state.athlete=$('#athleteName',d).value.trim()||'Pilot Athlete';state.settings.units=$('#units',d).value;save();d.close();toast('Settings saved');if(currentRoute==='home')renderHome()};$('#resetData',d).onclick=()=>{if(confirm('Reset all High Mileage pilot logs and feedback on this device?')){state=defaultState();save();d.close();setRoute('home');toast('Pilot data reset')}};d.showModal()}
document.addEventListener('click',e=>{const r=e.target.closest('[data-route]')?.dataset.route;if(r)setRoute(r)});$('#settingsBtn').onclick=showSettings;
fetch('program-data.json').then(r=>r.json()).then(d=>{DATA=d;renderHome();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{})}).catch(()=>{$('#view').innerHTML='<div class="feedback-card"><h3>Program data could not load.</h3><p>Make sure all app files were uploaded together.</p></div>'});
